version: '3.4'

services:
  zk-1: &zk
    image: confluentinc/cp-zookeeper:4.0.0
    env_file:
      - zk-common.env
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;zk-2:2888:3888;zk-3:2888:3888
    volumes:
      - zk-1:/var/lib/zookeeper/data
  zk-2:
    <<: *zk
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zk-1:2888:3888;0.0.0.0:2888:3888;zk-3:2888:3888
    volumes:
      - zk-2:/var/lib/zookeeper/data
  zk-3:
    <<: *zk
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zk-1:2888:3888;zk-2:2888:3888;0.0.0.0:2888:3888
    volumes:
      - zk-3:/var/lib/zookeeper/data

  kafka-1: &kafka
    image: confluentinc/cp-kafka:4.0.0
    env_file:
      - kafka-common.env
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9192,EXTERNAL://35.189.130.4:9092
      KAFKA_JMX_HOSTNAME: kafka-1
    ports:
      - 9092:9092
    volumes:
      - kafka-1:/var/lib/kafka/data
      - ./:/data
      - ./aws:/root/.aws

  kafka-2:
    <<: *kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9192,EXTERNAL://35.189.130.4:9093
      KAFKA_JMX_HOSTNAME: kafka-2
    ports:
      - 9093:9092
    volumes:
      - kafka-2:/var/lib/kafka/data
      - ./:/data
      - ./aws:/root/.aws

  kafka-3:
    <<: *kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9192,EXTERNAL://35.189.130.4:9094
      KAFKA_JMX_HOSTNAME: kafka-3
    ports:
      - 9094:9092
    volumes:
      - kafka-3:/var/lib/kafka/data
      - ./:/data
      - ./aws:/root/.aws

  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: zk-1:2181,zk-2:2181,zk-3:2181
      JMX_PORT: 9181
      APPLICATION_SECRET: letmein
    ports:
      - 9000:9000

  #schema-registry:
   # hostname: schema-registry
    #image: confluentinc/cp-schema-registry:5.0.1
    #container_name: schema-registry
    #links:
     # - kafka-1
     # - kafka-2
     # - kafka-3
     # - zk-1
     # - zk-2
     # - zk-3
    #ports:
     # - "8081:8081"
    #environment:
     # SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zk-1:2181,zk-2:2181,zk-3:2181"
      #SCHEMA_REGISTRY_HOST_NAME: schema-registry

  

volumes:
  zk-1:
  zk-2:
  zk-3:
  kafka-1:
  kafka-2:
  kafka-3:
